name: ci
on:
  workflow_dispatch:

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
    - name: Run tests
      run: mvn clean package

  security-scans:
    name: checkmarx-scans
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - name: Checkmarx One CLI Action
      uses: checkmarx/ast-github-action@main #Github Action version
      with:
        project_name: ${{ github.repository }}
        cx_tenant: ${{ secrets.CX_TENANT_NAME }}
        base_uri: ${{ secrets.CX_BASE_URI }}
        cx_client_id: ${{ secrets.CX_CLIENT_ID }}
        cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        branch: ${{ github.ref }}
        additional_params: '--scan-types sast,sca,container-security'
